# These are supported funding model platforms

github: radio-rogal
ko_fi: radio_rogal
liberapay: radio_rogal
issuehunt: radio-rogal
custom: [ "https://send.monobank.ua/jar/9r5bd6ejUC?f=enabled&t=slf4j-aws-lambda" ]
