variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dmaven.compiler.showWarnings=false -Dmaven.compiler.debug=false -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS"

image: amazoncorretto:11

include:
  - template: Security/SAST.gitlab-ci.yml

cache:
  paths:
    - .m2/repository
    - core/target
    - logger/target
    - json-logger/target

stages:
  - build
  - test
  - verify
  - release
  - deploy

build:
  stage: build
  script:
    - ./mvnw $MAVEN_CLI_OPTS clean compile
  rules:
    - if: $CI_COMMIT_TAG == null

test:
  stage: test
  script:
    - ./mvnw $MAVEN_CLI_OPTS verify
  artifacts:
    reports:
      junit:
        - core/target/surefire-reports/TEST-*.xml
        - logger/target/failsafe-reports/TEST-*.xml
        - json-logger/target/failsafe-reports/TEST-*.xml
  rules:
    - if: $CI_COMMIT_TAG == null

sast:
  stage: test
  variables:
    SAST_EXCLUDED_PATHS: jacoco-resources,prism.js

semgrep-sast:
  rules:
    - if: $CI_COMMIT_TAG == null

coverage:
  stage: verify
  script:
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' */target/site/jacoco/jacoco.csv
  coverage: '/(\d+\.?\d*) \% covered/'
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH && $CI_COMMIT_TAG == null

codacy:
  stage: verify
  script:
    - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r core/target/site/jacoco/jacoco.xml -r logger/target/site/jacoco/jacoco.xml -r json-logger/target/site/jacoco/jacoco.xml
  rules:
    - if: $CODACY_PROJECT_TOKEN && $CI_COMMIT_TAG == null

release:
  stage: release
  script:
    - ./mvnw $MAVEN_CLI_OPTS -s ci_settings.xml -pl core,logger,json-logger,. -am -ntp -DskipTests -Dchangelist= -Pjavadocs,release
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_DEFAULT_BRANCH != $CI_COMMIT_BRANCH
      when: never
  cache:
    paths:
      - target

pages:
  stage: deploy
  script:
    - cp changelog.md src/site/markdown
    - cp contributing.md src/site/markdown
    - ./mvnw javadoc:aggregate -Dchangelist= -Pjavadocs
    - ./mvnw $MAVEN_CLI_OPTS -pl . -Dchangelist= -Psite
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_DEFAULT_BRANCH != $CI_COMMIT_BRANCH
      when: never
